name: Running Script

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  push_changes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set Git Config
      run: |
        git config --global user.email "emjayfactor@gmail.com" #your email in github
        git config --global user.name "mjfactor" #your username

    
    - name: Replace Keywords
      run: |
        python script.py #The target script file you want the run in the root repository 
        git add readme.md
        git commit -m "update"
        git push
